USE [master]
GO

/****** Object:  Database [ManterCursoAPI]    Script Date: 14/07/2022 17:19:44 ******/
CREATE DATABASE [ManterCursoAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ManterCursoAPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS02\MSSQL\DATA\ManterCursoAPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ManterCursoAPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS02\MSSQL\DATA\ManterCursoAPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ManterCursoAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ManterCursoAPI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET ARITHABORT OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ManterCursoAPI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ManterCursoAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ManterCursoAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ManterCursoAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ManterCursoAPI] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ManterCursoAPI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ManterCursoAPI] SET  MULTI_USER 
GO

ALTER DATABASE [ManterCursoAPI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ManterCursoAPI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ManterCursoAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ManterCursoAPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ManterCursoAPI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ManterCursoAPI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ManterCursoAPI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ManterCursoAPI] SET  READ_WRITE 
GO

